name: Dispatch

on: push

env:
  GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
  REPO: "repositoryPrime"

jobs:
  check-windows-stuff:
    runs-on: windows-latest
    if: false
    steps:
      - name: Query Folders
        run: |
          cd C:
          cd 'Program Files (x86)'
          cd 'Windows Kits'
          cd 10
          cd bin
          ls
          cd 10.0.22000.0
          cd x86
          ls
  dispatch:
    runs-on: ubuntu-latest
    if: true
    steps:
      - name: Repository Dispatch
        run: |
          gh api /repos/$GITHUB_REPOSITORY_OWNER/${{env.REPO}}/actions/workflows/receive-dispatch.yml/dispatches \
            --input - <<< '{"ref":"${{ github.ref }}"","inputs":{"branch":"dev","packageVersion":"1.2.4"}}'
        #uses: peter-evans/repository-dispatch@v1
        #with:
        #  token: ${{ secrets.REPO_ACCESS_TOKEN }}
        #  repository: rbrtkrgr/repositoryB
        #  event-type: update-local-packages
        #  client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "{{ github.repository }}", "branch": "dev", "packageVersion":"1.2.3" }'
