name: Dispatch

on: push

jobs:
  check-windows-stuff:
    runs-on: windows-latest
    steps:
      - name: Query Folders
        run: |
          cd C:
          cd 'Program Files (x86)'
          cd 'Windows Kits'
          cd 10
          cd bin
          ls
          cd 10.0.22000.0
          cd x86
          ls
  dispatch:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: rbrtkrgr/repositoryB
          event-type: update-local-packages
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "repository": "{{ github.repository }}", "branch": "dev", "packageVersion":"1.2.3" }'
