name: Test Publishing

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Establish Variable
      run: |
        branch="GA"
        echo "branch=${branch}" >> $GITHUB_OUTPUT
    - name: Runs on Pre-Release
      if: 'github.event.release.prerelease'
      run: |
        echo "This is a Pre-Release"
        branch="EA"
        echo "branch=${branch}" >> $GITHUB_OUTPUT
    - name: Runs on Release
      if: '!github.event.release.prerelease'
      run: echo "This is a Release"
    - name: Debugging
      run: |
        echo "Branch: ${{ env.branch }}"
        echo "Release Name: ${{ github.event.release.name }}"
        echo "Prerelease: ${{ github.event.release.prerelease }}"
        echo "Event Name: ${{ github.event_name }}"
