name: Test Publishing

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BRANCH: "GA"
    steps:
    - name: Establish Variable
      run: |
        echo "Branch: $BRANCH"
    - name: Runs on Pre-Release
      if: 'github.event.release.prerelease'
      run: |
        echo "This is a Pre-Release"
        BRANCH="EA"
        echo "New Branch: $BRANCH"
    - name: Runs on Release
      if: '!github.event.release.prerelease'
      run: echo "This is a Release"
    - name: Debugging
      run: |
        echo "Branch: $BRANCH"
        echo "Release Name: ${{ github.event.release.name }}"
        echo "Prerelease: ${{ github.event.release.prerelease }}"
        echo "Event Name: ${{ github.event_name }}"
