name: Test Publishing

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Runs on Pre-Release
      if: 'github.event.release.prerelease'
      run: echo "This is a Pre-Release"
    - name: Runs on Release
      if: '!github.event.release.prerelease'
      run: echo "This is a Release"
    - name: Debugging
      run: |
        echo "Release Name: ${{ github.event.release.name }}"
        echo "Prerelease: ${{ github.event.release.prerelease }}"
        echo "Event Name: ${{ github.event_name }}"
