name: Test Publishing

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Runs on Pre-Release
      if: 'github.event.prerelease'
      run: echo "This is a Pre-Release"
    - name: Runs on Release
      if: '!github.event.prerelease'
      run: echo "This is a Release"
    - name: Debugging
      run: |
        echo ${{ github.event.release }}
        echo ${{ github.event.release.name }}
        echo ${{ github.event.release.type }}
        echo ${{ github.event.release.prerelease }}
        echo ${{ github.event.release.tag }}
        echo ${{ github.event.prerelease }}
        echo ${{ github.event.release }}
        echo ${{ github.event_name }}
