name: Test Publishing

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BRANCH: "GA"
      PRERELEASE: false
      RELEASE: false
    steps:
    - name: Runs on Pre-Release
      if: 'github.event.release.prerelease'
      run: |
        echo "This is a Pre-Release"
        echo "BRANCH=EA" >> $GITHUB_ENV
        echo "PRERELEASE=true" >> $GITHUB_ENV
    - name: Runs on Release
      if: '!github.event.release.prerelease'
      run: |
        echo "This is a Release"
        echo "RELEASE=true" >> $GITHUB_ENV
    - name: Debugging
      run: |
        echo "Branch: $BRANCH"
        echo "Branch: ${{ env.BRANCH }}"
        echo "Release Name: ${{ github.event.release.name }}"
        echo "Prerelease: ${{ github.event.release.prerelease }}"
        echo "Latest: ${{ github.event.release.latest }}"
        echo "Event Name: ${{ github.event_name }}"
        echo "Event Tag: ${{ github.event.release.tag }}"
        echo "Event Tag2: ${{ github.ref }}"
        echo "Event Tag3: ${{ github.event.release.tag_name }}"
        echo "Event Tag4: ${{ github.event.tag }}"
        
        
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Tag Prerelease
      if: ${{ env.PRERELEASE == 'true' }}
      run: |
        echo "Creating a Pre-Release Tag"
        #TAG="0.8.1-beta"
        #git tag $TAG
        #git push origin $TAG
    - name: Tag Release
      if: ${{ env.RELEASE == 'true' }}
      run: |
        echo "Creating a Release Tag"
        #TAG="0.8-release"
        #git tag $TAG
        #git push origin $TAG
