name: Test Publishing

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Establish Variable
      run: |
        echo "BRANCH=GA" >> $GITHUB_ENV
    - name: Runs on Pre-Release
      if: 'github.event.release.prerelease'
      run: |
        echo "This is a Pre-Release"
        echo "Existing Branch: ${{ env.BRANCH }}"
        echo "Existing Branch2: $BRANCH"
        echo "BRANCH=EA" >> $GITHUB_ENV
        echo "New Branch: ${{ env.BRANCH }}"
        echo "New Branch2: $BRANCH"
    - name: Runs on Release
      if: '!github.event.release.prerelease'
      run: |
        echo "This is a Release"
    - name: Debugging
      run: |
        echo "Branch: $BRANCH"
        echo "Branch: ${{ env.BRANCH }}"
        echo "Release Name: ${{ github.event.release.name }}"
        echo "Prerelease: ${{ github.event.release.prerelease }}"
        echo "Event Name: ${{ github.event_name }}"
