name: Create Release

on:
  workflow_dispatch:
  push:
  #push:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  #REPO: "repositoryZero"

jobs:
  create-release:
    runs-on: windows-latest
    steps:
      - name: Create release
        id: create-release
        uses: actions/create-release@v1
        with:
          tag_name: 1.1.${{github.run_number}}
          release_name: 1.1.${{github.run_number}}
      - name: Remove release
        run: gh release delete 1.1.${{github.run_number}} -y
      
