name: Promote Dev to QA

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      old_tag_name:
        required: true

jobs:
  print-token:
    permissions: write-all
    name: print-token
    environment: dev
    # needs: pre-pkr
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Get registration token
        id: getRegToken
        run: |
          curl -X POST -H \"Accept: application/vnd.github.v3+json\"  -H 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://api.github.com/repos/myprofile/myrepo/actions/runners/registration-token

  rename_tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout your repository code
        with:
          fetch-depth: 0

      - name: Get commit SHA of old tag
        id: get_sha
        run: echo "COMMIT_SHA=$(git rev-parse ${{ inputs.old_tag_name }})" >> $GITHUB_OUTPUT
        
      - name: Delete old tag
        run: |
          git tag -d ${{ inputs.old_tag_name }}
          git push origin :${{ inputs.old_tag_name }}
          
      - name: Create QA Pre-release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{inputs.old_tag_name}}-beta
          release_name:  ${{inputs.old_tag_name}}-beta
          prerelease: true
          commitish: ${{ steps.get_sha.outputs.COMMIT_SHA }}

      - name: Create and push new tag
        if: false
        run: |
          git tag ${{ inputs.new_tag_name }} ${{ steps.get_sha.outputs.COMMIT_SHA }}
          git push origin ${{ inputs.new_tag_name }}



