name: Reusable Workflow 2

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

defaults:
  run:
    shell: bash

jobs:
  reuse_worflow_1:
    uses: ./.github/workflows/reuse_1.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit
