name: Signed Commit Test

on:
  workflow_dispatch:

jobs:
  add-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Add File and Commit
        run: |
          touch newfile.txt
          git config --global user.email "rbrtkrgr@icloud.com"
          git config --global user.name "rbrtkrgr"
          git add newfile.txt
          git commit -m "Adding newfile.txt"
          git log
          git push
