name: JSON Array Template

on:
  workflow_call:
    inputs:
      languages:
        required: true
        type: string

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.setVariables.outputs.matrix }}
    steps:
      - id: setVariables
        run: |
          matrix=echo '$inputs' | jq -c 'split(",")'
          echo "matrix=$inputs" >> $GITHUB_OUTPUT
        env:
          inputs: ${{ inputs.languages }}
  analyze:
    name: Analyze
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        language: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - name: Initialize CodeQL
        run: |
          echo ${{ matrix.language }}
