name: Package Update

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true

env:
  PACKAGE_NAME: "Newtonsoft.Json"
  PACKAGE_VERSION: ${{inputs.version}} #"13.0.3"

jobs:
  detect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check Package Version
        id: check
        run: |
          if dotnet list package | grep -q "${{env.PACKAGE_NAME}}.*${{env.PACKAGE_VERSION}}"; then
            echo "Version 13.0.3 already installed"
            echo "match=false" >> $GITHUB_OUTPUT
          else
            echo "Version 13.0.3 needs to be installed"
            # dotnet add package Newtonsoft.Json --version 13.0.3
            echo "match=true" >> $GITHUB_OUTPUT
          fi
      - name: Create update branch
        if: steps.check.outputs.match == 'true'
        run: echo "Creating new branch for merge"
      - name: Skip update branch
        if: steps.check.outputs.match == 'false'
        run: echo "No update needed."
      - name: Check Git Status
        id: gitstatus
        run: | 
          if git status --porcelain | grep -q '\.csproj$'; then
            echo "Changed"
            changed=true
          else
            echo "Unchanged"
            changed=false
          fi
          echo "Changed: $changed"
          echo "changed=$changed" >> $GITHUB_OUTPUT
      - name: Make new branch
        if: steps.gitstatus.outputs.changed == 'true'
        run: echo "Making new branch based on Git Status"
      
